package com.minee.kotlin_sample2.part4chapter03.response.search

data class Poi(
    val id: String,
    val pKey: String,
    val navSeq: String,
    val collectionType: String,
    val name: String,
    val telNo: String,
    val frontLat: String,
    val frontLon: String,
    val noorLat: String,
    val noorLon: String,
    val upperAddrName: String,
    val middleAddrName: String,
    val lowerAddrName: String,
    val detailAddrName: String,
    val mlClass: String,
    val firstNo: String,
    val secondNo: String,
    val roadName: String,
    val firstBuildNo: String,
    val secondBuildNo: String,
    val radius: String,
    val upperBizName: String,
    val middleBizName: String,
    val lowerBizName: String,
    val detailBizName: String,
    val rpFlag: String,
    val groupSubLists: GroupSubLists,
    val newAddressList: NewAddressList,
)
